# One-off: insert geminiSources/geminiStudio namespaces into all 14 locales.
# Anchored at the trailing "  },\n} satisfies TranslationShape;" block.
import io
import os

LOCALES = ["zh-CN","zh-TW","en-US","ja-JP","de-DE","es-ES","fr-FR","it-IT","pl-PL","pt-BR","ru-RU","tr-TR","ca-ES","bn-IN"]

# (dotted key, {locale: text}) — {{x}} placeholders, i18next style.
KEYS = [
 ("geminiSources.newFolder", {"zh-CN":"新建文件夹","zh-TW":"新增資料夾","en-US":"New folder","ja-JP":"新規フォルダー","de-DE":"Neuer Ordner","es-ES":"Nueva carpeta","fr-FR":"Nouveau dossier","it-IT":"Nuova cartella","pl-PL":"Nowy folder","pt-BR":"Nova pasta","ru-RU":"Новая папка","tr-TR":"Yeni klasör","ca-ES":"Nova carpeta","bn-IN":"নতুন ফোল্ডার"}),
 ("geminiSources.addExisting", {"zh-CN":"从已有添加","zh-TW":"從現有新增","en-US":"Add existing","ja-JP":"既存を追加","de-DE":"Vorhandene hinzufügen","es-ES":"Añadir existentes","fr-FR":"Ajouter existant","it-IT":"Aggiungi esistenti","pl-PL":"Dodaj istniejące","pt-BR":"Adicionar existente","ru-RU":"Добавить существующие","tr-TR":"Mevcut olanları ekle","ca-ES":"Afegeix existents","bn-IN":"বিদ্যমান যোগ করুন"}),
 ("geminiSources.tabHierarchical", {"zh-CN":"层级资源 ({{count}})","zh-TW":"層級資源 ({{count}})","en-US":"Resources ({{count}})","ja-JP":"リソース ({{count}})","de-DE":"Ressourcen ({{count}})","es-ES":"Recursos ({{count}})","fr-FR":"Ressources ({{count}})","it-IT":"Risorse ({{count}})","pl-PL":"Zasoby ({{count}})","pt-BR":"Recursos ({{count}})","ru-RU":"Ресурсы ({{count}})","tr-TR":"Kaynaklar ({{count}})","ca-ES":"Recursos ({{count}})","bn-IN":"রিসোর্স ({{count}})"}),
 ("geminiSources.tabWebResearch", {"zh-CN":"网络导源","zh-TW":"網路導源","en-US":"Web research","ja-JP":"ウェブリサーチ","de-DE":"Web-Recherche","es-ES":"Investigación web","fr-FR":"Recherche web","it-IT":"Ricerca web","pl-PL":"Research w sieci","pt-BR":"Pesquisa na web","ru-RU":"Веб-поиск","tr-TR":"Web araştırması","ca-ES":"Recerca web","bn-IN":"ওয়েব রিসার্চ"}),
 ("geminiSources.selectAllForChat", {"zh-CN":"全选参与对话","zh-TW":"全選參與對話","en-US":"Select all for chat","ja-JP":"すべて会話に含める","de-DE":"Alle für den Chat auswählen","es-ES":"Seleccionar todo para el chat","fr-FR":"Tout sélectionner pour le chat","it-IT":"Seleziona tutto per la chat","pl-PL":"Zaznacz wszystko do czatu","pt-BR":"Selecionar tudo para o chat","ru-RU":"Выбрать всё для чата","tr-TR":"Sohbet için tümünü seç","ca-ES":"Selecciona-ho tot per al xat","bn-IN":"চ্যাটের জন্য সব নির্বাচন"}),
 ("geminiSources.deselectAll", {"zh-CN":"全不选","zh-TW":"全不選","en-US":"Deselect all","ja-JP":"すべて解除","de-DE":"Alle abwählen","es-ES":"Deseleccionar todo","fr-FR":"Tout désélectionner","it-IT":"Deseleziona tutto","pl-PL":"Odznacz wszystko","pt-BR":"Desmarcar tudo","ru-RU":"Снять всё","tr-TR":"Tümünün seçimini kaldır","ca-ES":"Desselecciona-ho tot","bn-IN":"সব নির্বাচন বাতিল"}),
 ("geminiSources.searchPlaceholder", {"zh-CN":"搜索资源...","zh-TW":"搜尋資源...","en-US":"Search resources...","ja-JP":"リソースを検索...","de-DE":"Ressourcen suchen...","es-ES":"Buscar recursos...","fr-FR":"Rechercher des ressources...","it-IT":"Cerca risorse...","pl-PL":"Szukaj zasobów...","pt-BR":"Pesquisar recursos...","ru-RU":"Поиск ресурсов...","tr-TR":"Kaynak ara...","ca-ES":"Cerca recursos...","bn-IN":"রিসোর্স খুঁজুন..."}),
 ("geminiSources.loadingTree", {"zh-CN":"加载资源目录中...","zh-TW":"載入資源目錄中...","en-US":"Loading resources...","ja-JP":"リソースを読み込み中...","de-DE":"Ressourcen werden geladen...","es-ES":"Cargando recursos...","fr-FR":"Chargement des ressources...","it-IT":"Caricamento risorse...","pl-PL":"Ładowanie zasobów...","pt-BR":"Carregando recursos...","ru-RU":"Загрузка ресурсов...","tr-TR":"Kaynaklar yükleniyor...","ca-ES":"Carregant recursos...","bn-IN":"রিসোর্স লোড হচ্ছে..."}),
 ("geminiSources.empty", {"zh-CN":"暂无知识资源，可点击右上角添加或通过网络导源探索","zh-TW":"尚無知識資源，可點右上角新增或透過網路導源探索","en-US":"No resources yet — add from the header or explore via web research","ja-JP":"リソースがありません。右上から追加するかウェブリサーチで探せます","de-DE":"Noch keine Ressourcen — oben hinzufügen oder per Web-Recherche suchen","es-ES":"Aún no hay recursos: añádelos arriba o explora con la investigación web","fr-FR":"Pas encore de ressources — ajoutez-les en haut ou explorez via la recherche web","it-IT":"Nessuna risorsa: aggiungine sopra o esplora con la ricerca web","pl-PL":"Brak zasobów — dodaj u góry lub poszukaj przez research w sieci","pt-BR":"Sem recursos ainda — adicione no topo ou explore pela pesquisa web","ru-RU":"Ресурсов пока нет — добавьте сверху или найдите через веб-поиск","tr-TR":"Henüz kaynak yok — üstten ekleyin veya web araştırmasıyla keşfedin","ca-ES":"Encara no hi ha recursos: afegeix-los a dalt o explora amb la recerca web","bn-IN":"এখনও কোনো রিসোর্স নেই — উপরে থেকে যোগ করুন বা ওয়েব রিসার্চে খুঁজুন"}),
 ("geminiSources.ungrouped", {"zh-CN":"未归档资源","zh-TW":"未歸檔資源","en-US":"Ungrouped","ja-JP":"未分類","de-DE":"Nicht gruppiert","es-ES":"Sin clasificar","fr-FR":"Non classés","it-IT":"Non raggruppati","pl-PL":"Niepogrupowane","pt-BR":"Não agrupados","ru-RU":"Без папки","tr-TR":"Grupsuz","ca-ES":"Sense classificar","bn-IN":"অগোষ্ঠীভুক্ত"}),
 ("geminiSources.folderBadgeMixed", {"zh-CN":"本笔记本 {{local}} 个 · 知识库共 {{total}} 个（{{missing}} 个未加入）","zh-TW":"本筆記本 {{local}} 個 · 知識庫共 {{total}} 個（{{missing}} 個未加入）","en-US":"{{local}} in this notebook · {{total}} in library ({{missing}} not added)","ja-JP":"このノートブックに {{local}} 件 · ライブラリ全体で {{total}} 件（未追加 {{missing}} 件）","de-DE":"{{local}} in diesem Notizbuch · {{total}} in der Bibliothek ({{missing}} nicht hinzugefügt)","es-ES":"{{local}} en este cuaderno · {{total}} en la biblioteca ({{missing}} sin añadir)","fr-FR":"{{local}} dans ce carnet · {{total}} dans la bibliothèque ({{missing}} non ajoutés)","it-IT":"{{local}} in questo notebook · {{total}} nella libreria ({{missing}} non aggiunti)","pl-PL":"{{local}} w tym notatniku · {{total}} w bibliotece ({{missing}} nie dodano)","pt-BR":"{{local}} neste caderno · {{total}} na biblioteca ({{missing}} não adicionados)","ru-RU":"{{local}} в этом блокноте · {{total}} в библиотеке ({{missing}} не добавлены)","tr-TR":"Bu defterde {{local}} · kütüphanede toplam {{total}} ({{missing}} eklenmedi)","ca-ES":"{{local}} en aquest quadern · {{total}} a la biblioteca ({{missing}} sense afegir)","bn-IN":"এই নোটবুকে {{local}}টি · লাইব্রেরিতে মোট {{total}}টি ({{missing}}টি যোগ হয়নি)"}),
 ("geminiSources.folderBadgeLocal", {"zh-CN":"本笔记本 {{count}} 个","zh-TW":"本筆記本 {{count}} 個","en-US":"{{count}} in this notebook","ja-JP":"このノートブックに {{count}} 件","de-DE":"{{count}} in diesem Notizbuch","es-ES":"{{count}} en este cuaderno","fr-FR":"{{count}} dans ce carnet","it-IT":"{{count}} in questo notebook","pl-PL":"{{count}} w tym notatniku","pt-BR":"{{count}} neste caderno","ru-RU":"{{count}} в этом блокноте","tr-TR":"Bu defterde {{count}}","ca-ES":"{{count}} en aquest quadern","bn-IN":"এই নোটবুকে {{count}}টি"}),
 ("geminiSources.folderEmptyInNotebook", {"zh-CN":"该文件夹在当前笔记本中暂无资源","zh-TW":"該資料夾在目前筆記本中暫無資源","en-US":"This folder has no resources in this notebook yet","ja-JP":"このフォルダーにはこのノートブックのリソースがありません","de-DE":"Dieser Ordner enthält noch keine Ressourcen in diesem Notizbuch","es-ES":"Esta carpeta aún no tiene recursos en este cuaderno","fr-FR":"Ce dossier n'a pas encore de ressources dans ce carnet","it-IT":"Questa cartella non ha ancora risorse in questo notebook","pl-PL":"Ten folder nie ma jeszcze zasobów w tym notatniku","pt-BR":"Esta pasta ainda não tem recursos neste caderno","ru-RU":"В этой папке пока нет ресурсов в этом блокноте","tr-TR":"Bu klasörde bu deftere ait kaynak yok","ca-ES":"Aquesta carpeta encara no té recursos en aquest quadern","bn-IN":"এই ফোল্ডারে এই নোটবুকে এখনও কোনো রিসোর্স নেই"}),
 ("geminiSources.folderTotalCount", {"zh-CN":"该文件夹总来源数: {{count}}","zh-TW":"該資料夾總來源數: {{count}}","en-US":"Total sources in folder: {{count}}","ja-JP":"フォルダー内のソース総数: {{count}}","de-DE":"Quellen im Ordner gesamt: {{count}}","es-ES":"Fuentes totales en la carpeta: {{count}}","fr-FR":"Sources totales dans le dossier : {{count}}","it-IT":"Fonti totali nella cartella: {{count}}","pl-PL":"Źródła w folderze łącznie: {{count}}","pt-BR":"Fontes totais na pasta: {{count}}","ru-RU":"Всего источников в папке: {{count}}","tr-TR":"Klasördeki toplam kaynak: {{count}}","ca-ES":"Fonts totals a la carpeta: {{count}}","bn-IN":"ফোল্ডারে মোট সোর্স: {{count}}"}),
 ("geminiSources.addNewResource", {"zh-CN":"添加新资源","zh-TW":"新增新資源","en-US":"Add new resource","ja-JP":"新規リソースを追加","de-DE":"Neue Ressource hinzufügen","es-ES":"Añadir nuevo recurso","fr-FR":"Ajouter une ressource","it-IT":"Aggiungi nuova risorsa","pl-PL":"Dodaj nowy zasób","pt-BR":"Adicionar novo recurso","ru-RU":"Добавить новый ресурс","tr-TR":"Yeni kaynak ekle","ca-ES":"Afegeix un recurs nou","bn-IN":"নতুন রিসোর্স যোগ করুন"}),
 ("geminiSources.webResearchTitle", {"zh-CN":"智能网络导源","zh-TW":"智慧網路導源","en-US":"Web research","ja-JP":"ウェブリサーチ","de-DE":"Web-Recherche","es-ES":"Investigación web","fr-FR":"Recherche web","it-IT":"Ricerca web","pl-PL":"Research w sieci","pt-BR":"Pesquisa na web","ru-RU":"Веб-поиск","tr-TR":"Web araştırması","ca-ES":"Recerca web","bn-IN":"ওয়েব রিসার্চ"}),
 ("geminiSources.fastMode", {"zh-CN":"快速","zh-TW":"快速","en-US":"Fast","ja-JP":"高速","de-DE":"Schnell","es-ES":"Rápido","fr-FR":"Rapide","it-IT":"Veloce","pl-PL":"Szybkie","pt-BR":"Rápido","ru-RU":"Быстрый","tr-TR":"Hızlı","ca-ES":"Ràpid","bn-IN":"দ্রুত"}),
 ("geminiSources.deepMode", {"zh-CN":"深度","zh-TW":"深度","en-US":"Deep","ja-JP":"深掘り","de-DE":"Tief","es-ES":"Profundo","fr-FR":"Approfondi","it-IT":"Profondo","pl-PL":"Dogłębne","pt-BR":"Profundo","ru-RU":"Глубокий","tr-TR":"Derin","ca-ES":"Profund","bn-IN":"গভীর"}),
 ("geminiSources.fastModeDesc", {"zh-CN":"秒级响应：提取关键词并发检索，清洗正文后一键勾选沉淀为来源。","zh-TW":"秒級回應：提取關鍵詞並行檢索，清洗正文後一鍵勾選沉澱為來源。","en-US":"Seconds to answer: extracts keywords, searches in parallel, cleans full text — tick pages to save as sources.","ja-JP":"数秒で応答：キーワードを抽出して並列検索し、本文を整形してソースとして保存できます。","de-DE":"Antwort in Sekunden: extrahiert Schlüsselwörter, sucht parallel, säubert den Text — Seiten als Quellen speichern.","es-ES":"Respuesta en segundos: extrae palabras clave, busca en paralelo y limpia el texto para guardar páginas como fuentes.","fr-FR":"Réponse en secondes : extrait les mots-clés, cherche en parallèle, nettoie le texte — cochez des pages pour les enregistrer comme sources.","it-IT":"Risposta in secondi: estrae parole chiave, cerca in parallelo e pulisce il testo — seleziona pagine per salvarle come fonti.","pl-PL":"Odpowiedź w kilka sekund: wyodrębnia słowa kluczowe, szuka równolegle i czyści tekst — zaznacz strony, aby zapisać jako źródła.","pt-BR":"Resposta em segundos: extrai palavras-chave, busca em paralelo e limpa o texto — marque páginas para salvar como fontes.","ru-RU":"Ответ за секунды: извлекает ключевые слова, ищет параллельно, чистит текст — отмечайте страницы, чтобы сохранить как источники.","tr-TR":"Saniyeler içinde: anahtar kelimeleri çıkarır, paralel arar, metni temizler — sayfaları kaynak olarak kaydedin.","ca-ES":"Resposta en segons: extreu paraules clau, cerca en paral·lel i neteja el text — marca pàgines per desar-les com a fonts.","bn-IN":"সেকেন্ডে উত্তর: কীওয়ার্ড বের করে, সমান্তরাল খোঁজে, টেক্সট পরিষ্কার করে — পেজগুলো সোর্স হিসেবে সংরক্ষণ করুন।"}),
 ("geminiSources.deepModeDesc", {"zh-CN":"深度智能体：长链路自主规划、多跳检索与交叉验证，输出结构化报告并导入来源。","zh-TW":"深度智慧體：長鏈路自主規劃、多跳檢索與交叉驗證，輸出結構化報告並匯入來源。","en-US":"Deep agent: autonomous planning, multi-hop retrieval and cross-validation, imports a structured report as sources.","ja-JP":"ディープエージェント：自律的に計画し、多段階の検索と相互検証を行い、構造化レポートをソースとして取り込みます。","de-DE":"Deep-Agent: plant eigenständig, sucht mehrstufig und kreuzvalidiert — importiert einen strukturierten Bericht als Quellen.","es-ES":"Agente profundo: planifica de forma autónoma, recupera en múltiples saltos y valida cruzando; importa un informe estructurado como fuentes.","fr-FR":"Agent approfondi : planification autonome, récupération multi-sauts et validation croisée — importe un rapport structuré comme sources.","it-IT":"Agente profondo: pianifica in autonomia, recupera multi-hop e valida incrociando, importando un report strutturato come fonti.","pl-PL":"Agent dogłębny: autonomiczne planowanie, wyszukiwanie wieloetapowe i walidacja krzyżowa — importuje ustrukturyzowany raport jako źródła.","pt-BR":"Agente profundo: planeja de forma autônoma, busca em múltiplos saltos e valida cruzando — importa um relatório estruturado como fontes.","ru-RU":"Глубокий агент: автономное планирование, многошаговый поиск и перекрёстная проверка — импортирует структурированный отчёт как источники.","tr-TR":"Derin ajan: otonom planlama, çok adımlı arama ve çapraz doğrulama — yapılandırılmış raporu kaynak olarak içe aktarır.","ca-ES":"Agent profund: planifica de forma autònoma, recupera en múltiples salts i valida creuant — importa un informe estructurat com a fonts.","bn-IN":"ডিপ এজেন্ট: স্বায়ত্ত পরিকল্পনা, মাল্টি-হপ অনুসন্ধান ও ক্রস-ভ্যালিডেশন — স্ট্রাকচার্ড রিপোর্ট সোর্স হিসেবে আনে।"}),
 ("geminiSources.fastPlaceholder", {"zh-CN":"输入探索关键词或课题...","zh-TW":"輸入探索關鍵詞或課題...","en-US":"Enter a keyword or topic...","ja-JP":"キーワードやテーマを入力...","de-DE":"Schlüsselwort oder Thema eingeben...","es-ES":"Introduce una palabra clave o tema...","fr-FR":"Saisissez un mot-clé ou un sujet...","it-IT":"Inserisci una parola chiave o un argomento...","pl-PL":"Wpisz słowo kluczowe lub temat...","pt-BR":"Digite uma palavra-chave ou tópico...","ru-RU":"Введите ключевое слово или тему...","tr-TR":"Bir anahtar kelime veya konu girin...","ca-ES":"Introdueix una paraula clau o tema...","bn-IN":"কীওয়ার্ড বা বিষয় লিখুন..."}),
 ("geminiSources.deepPlaceholder", {"zh-CN":"输入深度研究主题...","zh-TW":"輸入深度研究主題...","en-US":"Enter a deep research topic...","ja-JP":"深掘り調査のテーマを入力...","de-DE":"Thema für die Tiefenrecherche eingeben...","es-ES":"Introduce un tema de investigación profunda...","fr-FR":"Saisissez un sujet de recherche approfondie...","it-IT":"Inserisci un argomento di ricerca approfondita...","pl-PL":"Wpisz temat dogłębnego researchu...","pt-BR":"Digite um tópico de pesquisa profunda...","ru-RU":"Введите тему глубокого исследования...","tr-TR":"Derin araştırma konusunu girin...","ca-ES":"Introdueix un tema de recerca profunda...","bn-IN":"গভীর গবেষণার বিষয় লিখুন..."}),
 ("geminiSources.foundSources", {"zh-CN":"已搜寻到的优质来源 ({{count}})","zh-TW":"已搜尋到的優質來源 ({{count}})","en-US":"Quality sources found ({{count}})","ja-JP":"見つかった良質なソース ({{count}})","de-DE":"Gefundene Qualitätsquellen ({{count}})","es-ES":"Fuentes de calidad encontradas ({{count}})","fr-FR":"Sources de qualité trouvées ({{count}})","it-IT":"Fonti di qualità trovate ({{count}})","pl-PL":"Znalezione wartościowe źródła ({{count}})","pt-BR":"Fontes de qualidade encontradas ({{count}})","ru-RU":"Найденные качественные источники ({{count}})","tr-TR":"Bulunan kaliteli kaynaklar ({{count}})","ca-ES":"Fonts de qualitat trobades ({{count}})","bn-IN":"পাওয়া মানসম্পন্ন সোর্স ({{count}})"}),
 ("geminiSources.importing", {"zh-CN":"入库中...","zh-TW":"入庫中...","en-US":"Importing...","ja-JP":"取り込み中...","de-DE":"Wird importiert...","es-ES":"Importando...","fr-FR":"Importation...","it-IT":"Importazione...","pl-PL":"Importowanie...","pt-BR":"Importando...","ru-RU":"Импорт...","tr-TR":"İçe aktarılıyor...","ca-ES":"S'està important...","bn-IN":"ইমপোর্ট হচ্ছে..."}),
 ("geminiSources.bulkAdd", {"zh-CN":"批量加入笔记本","zh-TW":"批次加入筆記本","en-US":"Add all to notebook","ja-JP":"まとめてノートブックに追加","de-DE":"Alle zum Notizbuch hinzufügen","es-ES":"Añadir todo al cuaderno","fr-FR":"Tout ajouter au carnet","it-IT":"Aggiungi tutto al notebook","pl-PL":"Dodaj wszystkie do notatnika","pt-BR":"Adicionar tudo ao caderno","ru-RU":"Добавить всё в блокнот","tr-TR":"Tümünü deftere ekle","ca-ES":"Afegeix-ho tot al quadern","bn-IN":"সব নোটবুকে যোগ করুন"}),
 ("geminiSources.researchFastDone", {"zh-CN":"探索完成，已抓取高质量来源","zh-TW":"探索完成，已擷取高品質來源","en-US":"Fast research done — quality sources fetched","ja-JP":"リサーチ完了 — 良質なソースを取得しました","de-DE":"Recherche abgeschlossen — Qualitätsquellen abgerufen","es-ES":"Investigación completada: fuentes de calidad obtenidas","fr-FR":"Recherche terminée — sources de qualité récupérées","it-IT":"Ricerca completata — fonti di qualità recuperate","pl-PL":"Research zakończony — pobrano wartościowe źródła","pt-BR":"Pesquisa concluída — fontes de qualidade obtidas","ru-RU":"Поиск завершён — качественные источники получены","tr-TR":"Araştırma tamamlandı — kaliteli kaynaklar alındı","ca-ES":"Recerca completada — fonts de qualitat obtingudes","bn-IN":"রিসার্চ সম্পন্ন — মানসম্পন্ন সোর্স পাওয়া গেছে"}),
 ("geminiSources.researchDeepDone", {"zh-CN":"深度研读完成，已形成结构化来源","zh-TW":"深度研讀完成，已形成結構化來源","en-US":"Deep research done — structured sources ready","ja-JP":"深掘りリサーチ完了 — 構造化ソースができました","de-DE":"Tiefenrecherche abgeschlossen — strukturierte Quellen fertig","es-ES":"Investigación profunda completada: fuentes estructuradas listas","fr-FR":"Recherche approfondie terminée — sources structurées prêtes","it-IT":"Ricerca approfondita completata — fonti strutturate pronte","pl-PL":"Dogłębny research zakończony — ustrukturyzowane źródła gotowe","pt-BR":"Pesquisa profunda concluída — fontes estruturadas prontas","ru-RU":"Глубокое исследование завершено — структурированные источники готовы","tr-TR":"Derin araştırma tamamlandı — yapılandırılmış kaynaklar hazır","ca-ES":"Recerca profunda completada — fonts estructurades a punt","bn-IN":"গভীর গবেষণা সম্পন্ন — স্ট্রাকচার্ড সোর্স প্রস্তুত"}),
 ("geminiSources.researchFailed", {"zh-CN":"网络搜索与导源失败，请稍后重试","zh-TW":"網路搜尋與導源失敗，請稍後重試","en-US":"Web search failed, please try again later","ja-JP":"ウェブ検索に失敗しました。後ほどお試しください","de-DE":"Websuche fehlgeschlagen, bitte später erneut versuchen","es-ES":"La búsqueda web falló; inténtalo de nuevo más tarde","fr-FR":"Échec de la recherche web, réessayez plus tard","it-IT":"Ricerca web non riuscita, riprova più tardi","pl-PL":"Wyszukiwanie w sieci nie powiodło się, spróbuj ponownie później","pt-BR":"A pesquisa na web falhou, tente novamente mais tarde","ru-RU":"Веб-поиск не удался, попробуйте позже","tr-TR":"Web araması başarısız oldu, lütfen sonra tekrar deneyin","ca-ES":"La cerca web ha fallat, torna-ho a provar més tard","bn-IN":"ওয়েব সার্চ ব্যর্থ, পরে আবার চেষ্টা করুন"}),
 ("geminiSources.selectAtLeastOne", {"zh-CN":"请至少勾选一个要加入笔记本的网页","zh-TW":"請至少勾選一個要加入筆記本的網頁","en-US":"Select at least one page to add","ja-JP":"追加するページを1つ以上選択してください","de-DE":"Wähle mindestens eine Seite zum Hinzufügen aus","es-ES":"Selecciona al menos una página para añadir","fr-FR":"Sélectionnez au moins une page à ajouter","it-IT":"Seleziona almeno una pagina da aggiungere","pl-PL":"Wybierz co najmniej jedną stronę do dodania","pt-BR":"Selecione ao menos uma página para adicionar","ru-RU":"Выберите хотя бы одну страницу для добавления","tr-TR":"Eklemek için en az bir sayfa seçin","ca-ES":"Selecciona almenys una pàgina per afegir","bn-IN":"যোগ করতে অন্তত একটি পেজ নির্বাচন করুন"}),
 ("geminiSources.savedPages", {"zh-CN":"成功将 {{count}} 个网页作为来源沉淀至笔记本","zh-TW":"成功將 {{count}} 個網頁作為來源沉澱至筆記本","en-US":"Added {{count}} pages as sources","ja-JP":"{{count}} 件のページをソースとしてノートブックに追加しました","de-DE":"{{count}} Seiten als Quellen zum Notizbuch hinzugefügt","es-ES":"Se añadieron {{count}} páginas como fuentes","fr-FR":"{{count}} pages ajoutées comme sources","it-IT":"{{count}} pagine aggiunte come fonti","pl-PL":"Dodano {{count}} stron jako źródła","pt-BR":"{{count}} páginas adicionadas como fontes","ru-RU":"Добавлено страниц как источников: {{count}}","tr-TR":"{{count}} sayfa kaynak olarak eklendi","ca-ES":"S'han afegit {{count}} pàgines com a fonts","bn-IN":"{{count}}টি পেজ সোর্স হিসেবে যোগ হয়েছে"}),
 ("geminiSources.addPagesFailed", {"zh-CN":"添加网页来源失败","zh-TW":"新增網頁來源失敗","en-US":"Failed to add pages as sources","ja-JP":"ページのソース追加に失敗しました","de-DE":"Seiten konnten nicht als Quellen hinzugefügt werden","es-ES":"Error al añadir páginas como fuentes","fr-FR":"Échec de l'ajout des pages comme sources","it-IT":"Impossibile aggiungere le pagine come fonti","pl-PL":"Nie udało się dodać stron jako źródła","pt-BR":"Falha ao adicionar páginas como fontes","ru-RU":"Не удалось добавить страницы как источники","tr-TR":"Sayfalar kaynak olarak eklenemedi","ca-ES":"No s'han pogut afegir les pàgines com a fonts","bn-IN":"পেজগুলো সোর্স হিসেবে যোগ করা যায়নি"}),
 ("geminiSources.mockTitleInsights", {"zh-CN":"{{topic}} 核心架构解析与行业实践综述","zh-TW":"{{topic}} 核心架構解析與產業實務綜述","en-US":"{{topic}}: core architecture and industry practices","ja-JP":"{{topic}} の核心アーキテクチャと業界事例の総覧","de-DE":"{{topic}}: Kernarchitektur und Branchenpraxis im Überblick","es-ES":"{{topic}}: arquitectura central y prácticas del sector","fr-FR":"{{topic}} : architecture centrale et pratiques du secteur","it-IT":"{{topic}}: architettura principale e pratiche del settore","pl-PL":"{{topic}}: architektura rdzenia i praktyka branżowa","pt-BR":"{{topic}}: arquitetura central e práticas do setor","ru-RU":"{{topic}}: обзор архитектуры и отраслевых практик","tr-TR":"{{topic}}: çekirdek mimari ve sektör uygulamaları","ca-ES":"{{topic}}: arquitectura central i pràctiques del sector","bn-IN":"{{topic}}: কোর আর্কিটেকচার ও ইন্ডাস্ট্রি প্র্যাকটিস"}),
 ("geminiSources.mockSnippetInsights", {"zh-CN":"针对 {{topic}} 的深度调研，系统剖析核心机制、关键性能指标与工业级部署经验。","zh-TW":"針對 {{topic}} 的深度調研，系統剖析核心機制、關鍵效能指標與工業級部署經驗。","en-US":"In-depth survey of {{topic}}: core mechanisms, key performance metrics and production deployment lessons.","ja-JP":"{{topic}} の詳細調査：核心メカニズム、主要パフォーマンス指標、本番運用の知見を体系的に解説。","de-DE":"Tiefenanalyse zu {{topic}}: Kernmechanismen, wichtige Kennzahlen und Erfahrungen aus dem Produktionseinsatz.","es-ES":"Estudio en profundidad de {{topic}}: mecanismos centrales, métricas clave y experiencia de despliegue en producción.","fr-FR":"Étude approfondie de {{topic}} : mécanismes centraux, indicateurs clés et retour d'expérience de production.","it-IT":"Analisi approfondita di {{topic}}: meccanismi centrali, metriche chiave ed esperienze di deployment in produzione.","pl-PL":"Dogłębna analiza {{topic}}: mechanizmy rdzeniowe, kluczowe metryki i doświadczenia z wdrożeń produkcyjnych.","pt-BR":"Análise profunda de {{topic}}: mecanismos centrais, métricas-chave e experiência de implantação em produção.","ru-RU":"Глубокий обзор {{topic}}: ключевые механизмы, важные метрики и опыт промышленного развёртывания.","tr-TR":"{{topic}} üzerine derin inceleme: çekirdek mekanizmalar, kilit metrikler ve üretime geçiş deneyimi.","ca-ES":"Anàlisi en profunditat de {{topic}}: mecanismes centrals, mètriques clau i experiència de desplegament en producció.","bn-IN":"{{topic}}-এর গভীর জরিপ: কোর মেকানিজম, মূল মেট্রিক ও প্রোডাকশন ডিপ্লয়মেন্ট অভিজ্ঞতা।"}),
 ("geminiSources.mockTitleSpec", {"zh-CN":"{{topic}} 官方技术白皮书与最佳实践指南","zh-TW":"{{topic}} 官方技術白皮書與最佳實務指南","en-US":"{{topic}} official whitepaper and best practices","ja-JP":"{{topic}} 公式ホワイトペーパーとベストプラクティス","de-DE":"{{topic}} offizielles Whitepaper und Best Practices","es-ES":"{{topic}}: libro blanco oficial y buenas prácticas","fr-FR":"{{topic}} : livre blanc officiel et bonnes pratiques","it-IT":"{{topic}}: whitepaper ufficiale e best practice","pl-PL":"{{topic}}: oficjalny whitepaper i dobre praktyki","pt-BR":"{{topic}}: whitepaper oficial e boas práticas","ru-RU":"{{topic}}: официальный whitepaper и лучшие практики","tr-TR":"{{topic}} resmi teknik dokümanı ve en iyi uygulamalar","ca-ES":"{{topic}}: llibre blanc oficial i bones pràctiques","bn-IN":"{{topic}} অফিসিয়াল হোয়াইটপেপার ও সেরা অনুশীলন"}),
 ("geminiSources.mockSnippetSpec", {"zh-CN":"系统梳理了 {{topic}} 的设计决策、数据模型定义及常见性能陷阱防范。","zh-TW":"系統梳理了 {{topic}} 的設計決策、資料模型定義及常見效能陷阱防範。","en-US":"Systematic review of {{topic}} design decisions, data models and common performance pitfalls.","ja-JP":"{{topic}} の設計判断、データモデル定義、よくあるパフォーマンスの落とし穴を整理。","de-DE":"Systematischer Überblick über Designentscheidungen, Datenmodelle und typische Performance-Fallen bei {{topic}}.","es-ES":"Repaso sistemático de las decisiones de diseño, modelos de datos y trampas de rendimiento habituales de {{topic}}.","fr-FR":"Revue systématique des décisions de conception, modèles de données et pièges de performance courants de {{topic}}.","it-IT":"Rassegna sistematica delle decisioni di progettazione, dei modelli dati e delle insidie di prestazione comuni di {{topic}}.","pl-PL":"Systematyczny przegląd decyzji projektowych, modeli danych i typowych pułapek wydajnościowych {{topic}}.","pt-BR":"Revisão sistemática das decisões de projeto, modelos de dados e armadilhas de desempenho comuns do {{topic}}.","ru-RU":"Систематический разбор проектных решений, моделей данных и типичных ловушек производительности {{topic}}.","tr-TR":"{{topic}} tasarım kararlarının, veri modellerinin ve yaygın performans tuzaklarının sistematik incelemesi.","ca-ES":"Revisió sistemàtica de les decisions de disseny, models de dades i trampes de rendiment habituals de {{topic}}.","bn-IN":"{{topic}}-এর ডিজাইন সিদ্ধান্ত, ডেটা মডেল ও সাধারণ পারফরম্যান্স ফাঁদের পদ্ধতিগত পর্যালোচনা।"}),
 ("geminiSources.mockTitleBenchmark", {"zh-CN":"全景评测：{{topic}} 与主流开源方案的横向对比","zh-TW":"全景評測：{{topic}} 與主流開源方案的橫向對比","en-US":"Benchmark: {{topic}} versus mainstream open-source alternatives","ja-JP":"総合評価：{{topic}} と主要オープンソース方案の比較","de-DE":"Benchmark: {{topic}} im Vergleich mit gängigen Open-Source-Alternativen","es-ES":"Comparativa: {{topic}} frente a alternativas open source","fr-FR":"Comparatif : {{topic}} face aux alternatives open source","it-IT":"Confronto: {{topic}} rispetto alle alternative open source","pl-PL":"Porównanie: {{topic}} kontra popularne rozwiązania open source","pt-BR":"Comparativo: {{topic}} versus alternativas open source","ru-RU":"Сравнение: {{topic}} против популярных open-source-решений","tr-TR":"Karşılaştırma: {{topic}} ve önde gelen açık kaynak alternatifleri","ca-ES":"Comparativa: {{topic}} davant d'alternatives de codi obert","bn-IN":"তুলনা: {{topic}} বনাম জনপ্রিয় ওপেন-সোর্স বিকল্প"}),
 ("geminiSources.mockSnippetBenchmark", {"zh-CN":"基于真实吞吐量与长链路并发压力下的评测结论，揭示核心差异与场景选型推荐。","zh-TW":"基於真實吞吐量與長鏈路並發壓力下的評測結論，揭示核心差異與場景選型推薦。","en-US":"Conclusions from real throughput and sustained concurrency load, highlighting core differences and per-scenario picks.","ja-JP":"実際のスループットと長時間の並行負荷に基づく結論。核心的な違いと場面別の選定推奨を提示。","de-DE":"Ergebnisse aus echtem Durchsatz und Dauerlast: Kernunterschiede und Empfehlungen je Szenario.","es-ES":"Conclusiones con rendimiento real y carga concurrente prolongada: diferencias clave y recomendación por escenario.","fr-FR":"Conclusions sur débit réel et charge concurrentielle soutenue : différences clés et recommandations par scénario.","it-IT":"Conclusioni su throughput reale e carico concorrente prolungato: differenze chiave e consigli per scenario.","pl-PL":"Wnioski z rzeczywistej przepustowości i długotrwałego obciążenia: kluczowe różnice i rekomendacje per scenariusz.","pt-BR":"Conclusões com throughput real e carga concorrente prolongada: diferenças-chave e recomendação por cenário.","ru-RU":"Выводы по реальной пропускной способности и длительной параллельной нагрузке: ключевые отличия и рекомендации по сценариям.","tr-TR":"Gerçek verim ve sürekli eşzamanlı yük altındaki sonuçlar: temel farklar ve senaryoya göre öneriler.","ca-ES":"Conclusions amb rendiment real i càrrega concurrent sostinguda: diferències clau i recomanacions per escenari.","bn-IN":"বাস্তব থ্রুপুট ও দীর্ঘ কনকারেন্সি লোডের সিদ্ধান্ত: মূল পার্থক্য ও দৃশ্য অনুযায়ী সুপারিশ।"}),
 ("geminiSources.noViewError", {"zh-CN":"未找到可用视图","zh-TW":"未找到可用檢視","en-US":"No view available","ja-JP":"利用可能なビューがありません","de-DE":"Keine Ansicht verfügbar","es-ES":"No hay vista disponible","fr-FR":"Aucune vue disponible","it-IT":"Nessuna vista disponibile","pl-PL":"Brak dostępnego widoku","pt-BR":"Nenhuma visualização disponível","ru-RU":"Нет доступного представления","tr-TR":"Kullanılabilir görünüm yok","ca-ES":"Cap vista disponible","bn-IN":"কোনো ভিউ পাওয়া যায়নি"}),
 ("geminiSources.folderCreated", {"zh-CN":"文件夹创建成功","zh-TW":"資料夾建立成功","en-US":"Folder created","ja-JP":"フォルダーを作成しました","de-DE":"Ordner erstellt","es-ES":"Carpeta creada","fr-FR":"Dossier créé","it-IT":"Cartella creata","pl-PL":"Utworzono folder","pt-BR":"Pasta criada","ru-RU":"Папка создана","tr-TR":"Klasör oluşturuldu","ca-ES":"Carpeta creada","bn-IN":"ফোল্ডার তৈরি হয়েছে"}),
 ("geminiSources.folderCreateFailed", {"zh-CN":"创建文件夹失败","zh-TW":"建立資料夾失敗","en-US":"Failed to create folder","ja-JP":"フォルダーの作成に失敗しました","de-DE":"Ordner konnte nicht erstellt werden","es-ES":"Error al crear la carpeta","fr-FR":"Échec de la création du dossier","it-IT":"Impossibile creare la cartella","pl-PL":"Nie udało się utworzyć folderu","pt-BR":"Falha ao criar a pasta","ru-RU":"Не удалось создать папку","tr-TR":"Klasör oluşturulamadı","ca-ES":"No s'ha pogut crear la carpeta","bn-IN":"ফোল্ডার তৈরি করা যায়নি"}),
 ("geminiStudio.title", {"zh-CN":"Studio 工作室","zh-TW":"Studio 工作室","en-US":"Studio","ja-JP":"Studio","de-DE":"Studio","es-ES":"Studio","fr-FR":"Studio","it-IT":"Studio","pl-PL":"Studio","pt-BR":"Studio","ru-RU":"Studio","tr-TR":"Studio","ca-ES":"Studio","bn-IN":"Studio"}),
 ("geminiStudio.notesCount", {"zh-CN":"{{count}} 篇笔记","zh-TW":"{{count}} 篇筆記","en-US":"{{count}} notes","ja-JP":"ノート {{count}} 件","de-DE":"{{count}} Notizen","es-ES":"{{count}} notas","fr-FR":"{{count}} notes","it-IT":"{{count}} note","pl-PL":"{{count}} notatek","pt-BR":"{{count}} notas","ru-RU":"заметок: {{count}}","tr-TR":"{{count}} not","ca-ES":"{{count}} notes","bn-IN":"{{count}}টি নোট"}),
 ("geminiStudio.newNote", {"zh-CN":"新建笔记","zh-TW":"新增筆記","en-US":"New note","ja-JP":"新規ノート","de-DE":"Neue Notiz","es-ES":"Nueva nota","fr-FR":"Nouvelle note","it-IT":"Nuova nota","pl-PL":"Nowa notatka","pt-BR":"Nova nota","ru-RU":"Новая заметка","tr-TR":"Yeni not","ca-ES":"Nova nota","bn-IN":"নতুন নোট"}),
 ("geminiStudio.toolbox", {"zh-CN":"工具箱","zh-TW":"工具箱","en-US":"Toolbox","ja-JP":"ツールボックス","de-DE":"Werkzeugkasten","es-ES":"Caja de herramientas","fr-FR":"Boîte à outils","it-IT":"Cassetta degli attrezzi","pl-PL":"Przybornik","pt-BR":"Caixa de ferramentas","ru-RU":"Инструменты","tr-TR":"Araç kutusu","ca-ES":"Caixa d'eines","bn-IN":"টুলবক্স"}),
 ("geminiStudio.openTasks", {"zh-CN":"打开进度管理","zh-TW":"開啟進度管理","en-US":"Open tasks","ja-JP":"タスク管理を開く","de-DE":"Aufgabenverwaltung öffnen","es-ES":"Abrir tareas","fr-FR":"Ouvrir les tâches","it-IT":"Apri attività","pl-PL":"Otwórz zadania","pt-BR":"Abrir tarefas","ru-RU":"Открыть задачи","tr-TR":"Görevleri aç","ca-ES":"Obre les tasques","bn-IN":"টাস্ক খুলুন"}),
 ("geminiStudio.notesStream", {"zh-CN":"笔记卡片流 ({{count}})","zh-TW":"筆記卡片流 ({{count}})","en-US":"Notes ({{count}})","ja-JP":"ノートカード ({{count}})","de-DE":"Notizkarten ({{count}})","es-ES":"Tarjetas de notas ({{count}})","fr-FR":"Cartes de notes ({{count}})","it-IT":"Schede note ({{count}})","pl-PL":"Karty notatek ({{count}})","pt-BR":"Cartões de notas ({{count}})","ru-RU":"Карточки заметок ({{count}})","tr-TR":"Not kartları ({{count}})","ca-ES":"Targetes de notes ({{count}})","bn-IN":"নোট কার্ড ({{count}})"}),
 ("geminiStudio.saveHint", {"zh-CN":"可从对话一键沉淀","zh-TW":"可從對話一鍵沉澱","en-US":"Capture from chat in one click","ja-JP":"チャットからワンクリックで保存","de-DE":"Mit einem Klick aus dem Chat übernehmen","es-ES":"Captura del chat en un clic","fr-FR":"Capture depuis le chat en un clic","it-IT":"Cattura dalla chat in un clic","pl-PL":"Przechwyć z czatu jednym kliknięciem","pt-BR":"Capture do chat em um clique","ru-RU":"Сохранить из чата в один клик","tr-TR":"Sohbetten tek tıkla kaydet","ca-ES":"Captura del xat en un clic","bn-IN":"চ্যাট থেকে এক ক্লিকে সংরক্ষণ"}),
 ("geminiStudio.loadingNotes", {"zh-CN":"加载笔记中...","zh-TW":"載入筆記中...","en-US":"Loading notes...","ja-JP":"ノートを読み込み中...","de-DE":"Notizen werden geladen...","es-ES":"Cargando notas...","fr-FR":"Chargement des notes...","it-IT":"Caricamento note...","pl-PL":"Ładowanie notatek...","pt-BR":"Carregando notas...","ru-RU":"Загрузка заметок...","tr-TR":"Notlar yükleniyor...","ca-ES":"Carregant notes...","bn-IN":"নোট লোড হচ্ছে..."}),
 ("geminiStudio.emptyNotes", {"zh-CN":"暂无笔记卡片","zh-TW":"尚無筆記卡片","en-US":"No notes yet","ja-JP":"ノートはまだありません","de-DE":"Noch keine Notizen","es-ES":"Aún no hay notas","fr-FR":"Pas encore de notes","it-IT":"Ancora nessuna nota","pl-PL":"Brak notatek","pt-BR":"Nenhuma nota ainda","ru-RU":"Заметок пока нет","tr-TR":"Henüz not yok","ca-ES":"Encara no hi ha notes","bn-IN":"এখনও কোনো নোট নেই"}),
 ("geminiStudio.emptyNotesHint", {"zh-CN":"可在对话中点击「保存为笔记」，或划选关键文字一键沉淀至此处。","zh-TW":"可在對話中點擊「儲存為筆記」，或劃選關鍵文字一鍵沉澱至此處。","en-US":"Save a note from the chat, or select key text to capture it here.","ja-JP":"チャットで「ノートに保存」を選ぶか、重要な文を選択してここに保存できます。","de-DE":"Speichere eine Notiz aus dem Chat oder markiere Schlüsseltext, um ihn hier abzulegen.","es-ES":"Guarda una nota desde el chat o selecciona texto clave para capturarlo aquí.","fr-FR":"Enregistrez une note depuis le chat ou sélectionnez du texte clé pour le capturer ici.","it-IT":"Salva una nota dalla chat o seleziona testo chiave per catturarlo qui.","pl-PL":"Zapisz notatkę z czatu lub zaznacz kluczowy tekst, aby tu trafił.","pt-BR":"Salve uma nota do chat ou selecione texto-chave para capturá-lo aqui.","ru-RU":"Сохраните заметку из чата или выделите ключевой текст, чтобы добавить его сюда.","tr-TR":"Sohbetten bir not kaydedin veya önemli metni seçip buraya ekleyin.","ca-ES":"Desa una nota del xat o selecciona text clau per capturar-lo aquí.","bn-IN":"চ্যাট থেকে নোট সংরক্ষণ করুন বা মূল টেক্সট নির্বাচন করে এখানে যোগ করুন।"}),
 ("geminiStudio.noContent", {"zh-CN":"无内容","zh-TW":"無內容","en-US":"No content","ja-JP":"内容なし","de-DE":"Kein Inhalt","es-ES":"Sin contenido","fr-FR":"Aucun contenu","it-IT":"Nessun contenuto","pl-PL":"Brak treści","pt-BR":"Sem conteúdo","ru-RU":"Нет содержимого","tr-TR":"İçerik yok","ca-ES":"Sense contingut","bn-IN":"কোনো বিষয়বস্তু নেই"}),
 ("geminiStudio.generateFailed", {"zh-CN":"生成工件失败","zh-TW":"產生工件失敗","en-US":"Failed to generate artifact","ja-JP":"アーティファクトの生成に失敗しました","de-DE":"Artefakt konnte nicht generiert werden","es-ES":"Error al generar el artefacto","fr-FR":"Échec de la génération de l'artefact","it-IT":"Impossibile generare l'artefatto","pl-PL":"Nie udało się wygenerować artefaktu","pt-BR":"Falha ao gerar o artefato","ru-RU":"Не удалось сгенерировать артефакт","tr-TR":"Artifakt oluşturulamadı","ca-ES":"No s'ha pogut generar l'artefacte","bn-IN":"আর্টিফ্যাক্ট তৈরি করা যায়নি"}),
 ("geminiStudio.generateDone", {"zh-CN":"{{tool}} 生成成功，已作为笔记沉淀","zh-TW":"{{tool}} 產生成功，已作為筆記沉澱","en-US":"{{tool}} generated and saved as a note","ja-JP":"{{tool}} の生成が完了し、ノートとして保存しました","de-DE":"{{tool}} wurde generiert und als Notiz gespeichert","es-ES":"{{tool}} se generó y guardó como nota","fr-FR":"{{tool}} a été généré et enregistré comme note","it-IT":"{{tool}} generato e salvato come nota","pl-PL":"{{tool}} wygenerowano i zapisano jako notatkę","pt-BR":"{{tool}} gerado e salvo como nota","ru-RU":"{{tool}} сгенерирован и сохранён как заметка","tr-TR":"{{tool}} oluşturuldu ve not olarak kaydedildi","ca-ES":"{{tool}} s'ha generat i desat com a nota","bn-IN":"{{tool}} তৈরি হয়ে নোট হিসেবে সংরক্ষিত"}),
 ("geminiStudio.jobProgressTitle", {"zh-CN":"{{tool}} · 生成进度","zh-TW":"{{tool}} · 產生進度","en-US":"{{tool}} · progress","ja-JP":"{{tool}} · 生成進捗","de-DE":"{{tool}} · Fortschritt","es-ES":"{{tool}} · progreso","fr-FR":"{{tool}} · progression","it-IT":"{{tool}} · avanzamento","pl-PL":"{{tool}} · postęp","pt-BR":"{{tool}} · progresso","ru-RU":"{{tool}} · ход выполнения","tr-TR":"{{tool}} · ilerleme","ca-ES":"{{tool}} · progrés","bn-IN":"{{tool}} · অগ্রগতি"}),
 ("geminiStudio.jobProgressHint", {"zh-CN":"任务已在后台异步执行，可实时查看状态或跳转进度管理","zh-TW":"任務已在背景非同步執行，可即時檢視狀態或跳轉進度管理","en-US":"The job runs in the background — watch its progress or open the tasks center","ja-JP":"タスクはバックグラウンドで実行中です。状況を確認するかタスク管理へ移動できます","de-DE":"Der Auftrag läuft im Hintergrund — Status verfolgen oder Aufgabenverwaltung öffnen","es-ES":"La tarea se ejecuta en segundo plano: sigue su estado o abre la gestión de tareas","fr-FR":"La tâche s'exécute en arrière-plan — suivez son état ou ouvrez la gestion des tâches","it-IT":"L'attività è in esecuzione in background — controlla lo stato o apri la gestione attività","pl-PL":"Zadanie działa w tle — śledź postęp lub otwórz centrum zadań","pt-BR":"A tarefa roda em segundo plano — acompanhe o progresso ou abra o centro de tarefas","ru-RU":"Задача выполняется в фоне — следите за статусом или откройте центр задач","tr-TR":"Görev arka planda çalışıyor — durumu izleyin veya görev merkezini açın","ca-ES":"La tasca s'executa en segon pla — segueix-ne l'estat o obre el centre de tasques","bn-IN":"কাজটি ব্যাকগ্রাউন্ডে চলছে — অবস্থা দেখুন বা টাস্ক সেন্টার খুলুন"}),
 ("geminiStudio.instructionLabel", {"zh-CN":"生成指令与侧重点（可选）","zh-TW":"產生指令與側重點（可選）","en-US":"Instruction & focus (optional)","ja-JP":"指示と重点（任意）","de-DE":"Anweisung & Schwerpunkt (optional)","es-ES":"Instrucción y enfoque (opcional)","fr-FR":"Instruction et accent (facultatif)","it-IT":"Istruzione e focus (facoltativo)","pl-PL":"Instrukcja i nacisk (opcjonalnie)","pt-BR":"Instrução e foco (opcional)","ru-RU":"Инструкция и акцент (необязательно)","tr-TR":"Talimat ve odak (isteğe bağlı)","ca-ES":"Instrucció i enfocament (opcional)","bn-IN":"নির্দেশনা ও ফোকাস (ঐচ্ছিক)"}),
 ("geminiStudio.instructionPlaceholder", {"zh-CN":"输入给 AI 的定制指令或关注侧重点...","zh-TW":"輸入給 AI 的客製指令或關注側重點...","en-US":"Custom instruction or focus for the AI...","ja-JP":"AI へのカスタム指示や重点を入力...","de-DE":"Benutzerdefinierte Anweisung oder Schwerpunkt für die KI...","es-ES":"Instrucción personalizada o enfoque para la IA...","fr-FR":"Instruction personnalisée ou accent pour l'IA...","it-IT":"Istruzione personalizzata o focus per l'IA...","pl-PL":"Niestandardowa instrukcja lub nacisk dla AI...","pt-BR":"Instrução personalizada ou foco para a IA...","ru-RU":"Пользовательская инструкция или акцент для ИИ...","tr-TR":"YZ için özel talimat veya odak...","ca-ES":"Instrucció personalitzada o enfocament per a la IA...","bn-IN":"AI-এর জন্য কাস্টম নির্দেশনা বা ফোকাস..."}),
 ("geminiStudio.contextHint", {"zh-CN":"将基于当前选取的 {{count}} 个知识来源及相关笔记进行提炼生成，完成后自动沉淀为笔记。","zh-TW":"將基於目前選取的 {{count}} 個知識來源及相關筆記進行提煉產生，完成後自動沉澱為筆記。","en-US":"Generates from the {{count}} selected sources and related notes, then saves the result as a note.","ja-JP":"選択中の {{count}} 件のソースと関連ノートから生成し、完了後にノートとして保存します。","de-DE":"Wird aus den {{count}} ausgewählten Quellen und zugehörigen Notizen erzeugt und danach als Notiz gespeichert.","es-ES":"Se genera a partir de las {{count}} fuentes seleccionadas y notas relacionadas, y se guarda como nota al terminar.","fr-FR":"Génère à partir des {{count}} sources sélectionnées et des notes liées, puis enregistre le résultat comme note.","it-IT":"Genera dalle {{count}} fonti selezionate e note correlate, salvando il risultato come nota.","pl-PL":"Generuje z {{count}} wybranych źródeł i powiązanych notatek, a wynik zapisuje jako notatkę.","pt-BR":"Gera a partir das {{count}} fontes selecionadas e notas relacionadas, salvando o resultado como nota.","ru-RU":"Генерирует из {{count}} выбранных источников и связанных заметок, сохраняя результат как заметку.","tr-TR":"Seçili {{count}} kaynaktan ve ilgili notlardan üretir, sonucu not olarak kaydeder.","ca-ES":"Genera a partir de les {{count}} fonts seleccionades i notes relacionades, i desa el resultat com a nota.","bn-IN":"নির্বাচিত {{count}}টি সোর্স ও সংশ্লিষ্ট নোট থেকে তৈরি করে ফলাফল নোট হিসেবে সংরক্ষণ করে।"}),
 ("geminiStudio.runInBackground", {"zh-CN":"后台运行，关闭","zh-TW":"背景執行，關閉","en-US":"Run in background","ja-JP":"バックグラウンドで続行","de-DE":"Im Hintergrund fortfahren","es-ES":"Seguir en segundo plano","fr-FR":"Continuer en arrière-plan","it-IT":"Continua in background","pl-PL":"Kontynuuj w tle","pt-BR":"Continuar em segundo plano","ru-RU":"Продолжить в фоне","tr-TR":"Arka planda sürdür","ca-ES":"Continua en segon pla","bn-IN":"ব্যাকগ্রাউন্ডে চালিয়ে যান"}),
 ("geminiStudio.submitting", {"zh-CN":"正在提交任务...","zh-TW":"正在提交任務...","en-US":"Submitting...","ja-JP":"送信中...","de-DE":"Wird gesendet...","es-ES":"Enviando...","fr-FR":"Envoi...","it-IT":"Invio...","pl-PL":"Przesyłanie...","pt-BR":"Enviando...","ru-RU":"Отправка...","tr-TR":"Gönderiliyor...","ca-ES":"S'està enviant...","bn-IN":"জমা দেওয়া হচ্ছে..."}),
 ("geminiStudio.generateAndSave", {"zh-CN":"立即生成并存为笔记","zh-TW":"立即產生並存為筆記","en-US":"Generate & save as note","ja-JP":"生成してノートに保存","de-DE":"Erzeugen und als Notiz speichern","es-ES":"Generar y guardar como nota","fr-FR":"Générer et enregistrer comme note","it-IT":"Genera e salva come nota","pl-PL":"Wygeneruj i zapisz jako notatkę","pt-BR":"Gerar e salvar como nota","ru-RU":"Сгенерировать и сохранить как заметку","tr-TR":"Üret ve not olarak kaydet","ca-ES":"Genera i desa com a nota","bn-IN":"তৈরি করে নোট হিসেবে সংরক্ষণ"}),
 ("geminiStudio.tagPodcast", {"zh-CN":"播客","zh-TW":"播客","en-US":"Podcast","ja-JP":"ポッドキャスト","de-DE":"Podcast","es-ES":"Pódcast","fr-FR":"Podcast","it-IT":"Podcast","pl-PL":"Podcast","pt-BR":"Podcast","ru-RU":"Подкаст","tr-TR":"Podcast","ca-ES":"Podcast","bn-IN":"পডকাস্ট"}),
 ("geminiStudio.tagArtifact", {"zh-CN":"快捷工件","zh-TW":"快捷工件","en-US":"Artifact","ja-JP":"アーティファクト","de-DE":"Artefakt","es-ES":"Artefacto","fr-FR":"Artefact","it-IT":"Artefatto","pl-PL":"Artefakt","pt-BR":"Artefato","ru-RU":"Артефакт","tr-TR":"Artifakt","ca-ES":"Artefacte","bn-IN":"আর্টিফ্যাক্ট"}),
 ("geminiStudio.tools.audioOverview.desc", {"zh-CN":"生成双人主持的深度对谈音频播客（真实语音合成）","zh-TW":"產生雙人主持的深度對談音訊播客（真實語音合成）","en-US":"Two-host deep-dive audio podcast with real speech synthesis","ja-JP":"二人のホストによる掘り下げ音声ポッドキャスト（実際の音声合成）","de-DE":"Audio-Podcast mit zwei Moderatoren (echte Sprachsynthese)","es-ES":"Pódcast de análisis a fondo con dos presentadores (síntesis de voz real)","fr-FR":"Podcast d'analyse avec deux animateurs (synthèse vocale réelle)","it-IT":"Podcast di approfondimento con due conduttori (sintesi vocale reale)","pl-PL":"Podcast głębokiej analizy z dwoma prowadzącymi (prawdziwa synteza mowy)","pt-BR":"Podcast de análise com dois apresentadores (síntese de voz real)","ru-RU":"Подкаст с двумя ведущими (реальный синтез речи)","tr-TR":"İki sunuculu derin analiz podcasti (gerçek konuşma sentezi)","ca-ES":"Podcast d'anàlisi amb dos presentadors (síntesi de veu real)","bn-IN":"দুই উপস্থাপকের গভীর বিশ্লেষণ পডকাস্ট (আসল কথা সংশ্লেষ)"}),
 ("geminiStudio.tools.studyGuide.desc", {"zh-CN":"提炼核心概念、考试测验问答与系统复习大纲","zh-TW":"提煉核心概念、考試測驗問答與系統複習大綱","en-US":"Key concepts, quiz Q&A and a systematic review outline","ja-JP":"主要概念、クイズ形式のQ&A、体系的な復習アウトライン","de-DE":"Kernkonzepte, Quiz-Fragen und ein systematischer Wiederholungsplan","es-ES":"Conceptos clave, preguntas tipo test y esquema de repaso sistemático","fr-FR":"Concepts clés, QCM et plan de révision systématique","it-IT":"Concetti chiave, quiz Q&A e schema di ripasso sistematico","pl-PL":"Kluczowe pojęcia, pytania quizowe i systematyczny plan powtórki","pt-BR":"Conceitos-chave, perguntas de quiz e roteiro de revisão sistemático","ru-RU":"Ключевые понятия, тестовые вопросы и план систематического повторения","tr-TR":"Temel kavramlar, test soruları ve sistematik tekrar planı","ca-ES":"Conceptes clau, preguntes de test i esquema de repàs sistemàtic","bn-IN":"মূল ধারণা, কুইজ প্রশ্নোত্তর ও পদ্ধতিগত রিভিশন রূপরেখা"}),
 ("geminiStudio.tools.studyGuide.instruction", {"zh-CN":"请为我整理一份系统的学习指南，包含核心概念术语解析、关键要点总结以及自测选择题与简答题。","zh-TW":"請為我整理一份系統的學習指南，包含核心概念術語解析、關鍵要點總結以及自測選擇題與簡答題。","en-US":"Prepare a systematic study guide with key term analysis, essential takeaways, self-test multiple-choice and short-answer questions.","ja-JP":"体系的な学習ガイドを作成してください：主要用語の解説、要点のまとめ、自己テスト用の選択問題と記述問題を含めてください。","de-DE":"Erstelle einen systematischen Lernleitfaden mit Begriffserklärungen, Kernpunkten sowie Multiple-Choice- und Kurzfragen zum Selbsttest.","es-ES":"Prepara una guía de estudio sistemática con análisis de términos clave, resumen de puntos esenciales y preguntas tipo test y abiertas de autocomprobación.","fr-FR":"Prépare un guide d'étude systématique avec analyse des termes clés, résumé des points essentiels et questions à choix multiples et ouvertes d'auto-évaluation.","it-IT":"Prepara una guida di studio sistematica con analisi dei termini chiave, sintesi dei punti essenziali e domande a scelta multipla e aperte di autoverifica.","pl-PL":"Przygotuj systematyczny przewodnik do nauki z analizą kluczowych pojęć, podsumowaniem najważniejszych punktów oraz pytaniami testowymi i otwartymi do samosprawdzenia.","pt-BR":"Prepare um guia de estudos sistemático com análise dos termos-chave, resumo dos pontos essenciais e questões de múltipla escolha e dissertativas de autoavaliação.","ru-RU":"Составь систематическое учебное пособие с разбором ключевых терминов, сводкой главных тезисов и вопросами для самопроверки (тестовыми и открытыми).","tr-TR":"Anahtar terim analizi, önemli noktaların özeti ve kendi kendini test etmek için çoktan seçmeli ve açık uçlu sorular içeren sistematik bir çalışma rehberi hazırla.","ca-ES":"Prepara una guia d'estudi sistemàtica amb anàlisi de termes clau, resum dels punts essencials i preguntes d'elecció múltiple i obertes d'autoavaluació.","bn-IN":"মূল পরিভাষা বিশ্লেষণ, অত্যাবশ্যকীয় পয়েন্টের সারসংক্ষেপ ও আত্মমূল্যায়নের বহুনির্বাচনী ও সংক্ষিপ্ত প্রশ্নসহ পদ্ধতিগত অধ্যয়ন নির্দেশিকা তৈরি করুন।"}),
 ("geminiStudio.tools.briefingDoc.desc", {"zh-CN":"生成专业执行简报、关键论据、战略启示与结论","zh-TW":"產生專業執行簡報、關鍵論據、策略啟示與結論","en-US":"Executive briefing with key arguments, strategic implications and conclusions","ja-JP":"エグゼクティブブリーフィング：主要論拠、戦略的示唆、結論","de-DE":"Executive-Briefing mit Kernargumenten, strategischen Implikationen und Schlussfolgerungen","es-ES":"Informe ejecutivo con argumentos clave, implicaciones estratégicas y conclusiones","fr-FR":"Note de synthèse avec arguments clés, implications stratégiques et conclusions","it-IT":"Briefing executive con argomentazioni chiave, implicazioni strategiche e conclusioni","pl-PL":"Krótkie podsumowanie zarządcze z kluczowymi argumentami, implikacjami strategicznymi i wnioskami","pt-BR":"Briefing executivo com argumentos-chave, implicações estratégicas e conclusões","ru-RU":"Экспресс-обзор с ключевыми аргументами, стратегическими выводами и заключениями","tr-TR":"Kilit argümanlar, stratejik çıkarımlar ve sonuçlarla yönetici brifingi","ca-ES":"Informe executiu amb arguments clau, implicacions estratègiques i conclusions","bn-IN":"মূল যুক্তি, কৌশলগত প্রভাব ও সিদ্ধান্তসহ এক্সিকিউটিভ ব্রিফিং"}),
 ("geminiStudio.tools.briefingDoc.instruction", {"zh-CN":"请提炼一份专业的高管项目简报，包含背景摘要、关键支撑事实、潜在风险评估及后续行动建议。","zh-TW":"請提煉一份專業的高階主管專案簡報，包含背景摘要、關鍵支撐事實、潛在風險評估及後續行動建議。","en-US":"Draft a professional executive briefing with background summary, key supporting facts, risk assessment and recommended next steps.","ja-JP":"専門性の高いエグゼクティブ向けブリーフィングを作成してください：背景要約、主要な裏付け事実、リスク評価、次のアクション提案を含めてください。","de-DE":"Erstelle ein professionelles Executive-Briefing mit Hintergrundzusammenfassung, tragenden Fakten, Risikobewertung und empfohlenen nächsten Schritten.","es-ES":"Redacta un informe ejecutivo profesional con resumen del contexto, hechos de apoyo clave, evaluación de riesgos y próximos pasos recomendados.","fr-FR":"Rédige une note de synthèse professionnelle avec résumé du contexte, faits clés, évaluation des risques et prochaines étapes recommandées.","it-IT":"Redigi un briefing executive professionale con sintesi del contesto, fatti di supporto chiave, valutazione dei rischi e prossime azioni consigliate.","pl-PL":"Sporządź profesjonalne podsumowanie zarządcze ze streszczeniem tła, kluczowymi faktami, oceną ryzyka i zalecanymi następnych krokami.","pt-BR":"Elabore um briefing executivo profissional com resumo do contexto, fatos de apoio-chave, avaliação de riscos e próximas ações recomendadas.","ru-RU":"Составь профессиональный экспресс-обзор с резюме контекста, ключевыми фактами, оценкой рисков и рекомендациями по дальнейшим шагам.","tr-TR":"Bağlam özeti, kılavaytlar, risk değerlendirmesi ve önerilen sonraki adımlarla profesyonel bir yönetici brifingi hazırla.","ca-ES":"Redacta un informe executiu professional amb resum del context, fets clau de suport, avaluació de riscos i pròxims passos recomanats.","bn-IN":"প্রসঙ্গ সারসংক্ষেপ, মূল সহায়ক তথ্য, ঝুঁকি মূল্যায়ন ও পরবর্তী পদক্ষেপ সুপারিশসহ পেশাদার এক্সিকিউটিভ ব্রিফিং তৈরি করুন।"}),
 ("geminiStudio.tools.faq.desc", {"zh-CN":"基于来源提取最关键的常见问答与详细解答","zh-TW":"基於來源提取最關鍵的常見問答與詳細解答","en-US":"The most important FAQs with detailed answers from your sources","ja-JP":"ソースから最重要のFAQと詳細な回答を抽出","de-DE":"Die wichtigsten FAQs mit ausführlichen Antworten aus deinen Quellen","es-ES":"Las preguntas frecuentes más importantes con respuestas detalladas de tus fuentes","fr-FR":"Les FAQ les plus importantes avec réponses détaillées tirées de vos sources","it-IT":"Le domande frequenti più importanti con risposte dettagliate dalle tue fonti","pl-PL":"Najważniejsze pytania i odpowiedzi ze szczegółowymi wyjaśnieniami z Twoich źródeł","pt-BR":"As perguntas frequentes mais importantes com respostas detalhadas de suas fontes","ru-RU":"Самые важные вопросы и ответы с подробными разъяснениями из ваших источников","tr-TR":"Kaynaklarınızdan en önemli SSS'ler ve ayrıntılı yanıtlar","ca-ES":"Les preguntes freqüents més importants amb respostes detallades de les teves fonts","bn-IN":"আপনার সোর্স থেকে সবচেয়ে গুরুত্বপূর্ণ প্রশ্নোত্তর ও বিস্তারিত উত্তর"}),
 ("geminiStudio.tools.faq.instruction", {"zh-CN":"请全面梳理当前资料，整理出读者最常关心的核心问题与翔实解答。","zh-TW":"請全面梳理目前資料，整理出讀者最常關心的核心問題與翔實解答。","en-US":"Go through the materials and compile the most frequently asked questions with thorough answers.","ja-JP":"資料を全面的に確認し、読者が最も関心を持つ核心的な質問と十分な回答をまとめてください。","de-DE":"Gehe die Materialien durch und stelle die häufigsten Kernfragen mit fundierten Antworten zusammen.","es-ES":"Revisa todos los materiales y recopila las preguntas esenciales más frecuentes con respuestas exhaustivas.","fr-FR":"Parcours l'ensemble des documents et compile les questions essentielles les plus fréquentes avec des réponses approfondies.","it-IT":"Esamina tutti i materiali e raccogli le domande essenziali più frequenti con risposte approfondite.","pl-PL":"Przejrzyj materiały i zestaw najczęstsze kluczowe pytania z wyczerpującymi odpowiedziami.","pt-BR":"Revise todos os materiais e compile as perguntas essenciais mais frequentes com respostas exaustivas.","ru-RU":"Просмотри все материалы и собери самые частые ключевые вопросы с развёрнутыми ответами.","tr-TR":"Materyalleri gözden geçir ve en sık sorulan temel soruları kapsamlı yanıtlarla derle.","ca-ES":"Revisa tots els materials i recopila les preguntes essencials més freqüents amb respostes exhaustives.","bn-IN":"সব উপকরণ পর্যালোচনা করে পাঠকদের সবচেয়ে সাধারণ মূল প্রশ্নগুলো বিস্তারিত উত্তরসহ সংকলন করুন।"}),
 ("geminiStudio.tools.flashcards.desc", {"zh-CN":"提取核心知识点与问答对，生成正反面抽认记忆卡片","zh-TW":"提取核心知識點與問答對，產生正反面抽認記憶卡片","en-US":"Key knowledge as question/answer flashcard pairs","ja-JP":"核心知識をQ&Aペアのフラッシュカードに","de-DE":"Kernwissen als Frage-Antwort-Kartenpaare","es-ES":"Conocimiento clave en pares pregunta/respuesta tipo flashcards","fr-FR":"Connaissances clés en paires question/réponse façon flashcards","it-IT":"Conoscenze chiave come coppie domanda/risposta stile flashcard","pl-PL":"Kluczowa wiedza jako pary pytanie/odpowiedź w formie fiszek","pt-BR":"Conhecimento-chave em pares pergunta/resposta estilo flashcards","ru-RU":"Ключевые знания в виде карточек вопрос/ответ","tr-TR":"Temel bilgileri soru/cevap kart çiftleri haline getir","ca-ES":"Coneixement clau en parells pregunta/resposta tipus flashcards","bn-IN":"মূল জ্ঞানকে প্রশ্ন/উত্তর ফ্ল্যাশকার্ড জোড়া হিসেবে"}),
 ("geminiStudio.tools.flashcards.instruction", {"zh-CN":"请提炼核心概念与重要结论，生成便于记忆与抽认自测的问答知识卡片集。","zh-TW":"請提煉核心概念與重要結論，產生便於記憶與抽認自測的問答知識卡片集。","en-US":"Distill core concepts and conclusions into memorizable Q&A flashcards.","ja-JP":"主要概念と重要な結論を抽出し、暗記と自己テストに便利なQ&Aカードセットを作成してください。","de-DE":"Destilliere Kernkonzepte und Schlussfolgerungen in memorierbare Frage-Antwort-Karten.","es-ES":"Destila conceptos y conclusiones clave en tarjetas de preguntas y respuestas fáciles de memorizar.","fr-FR":"Distille les concepts et conclusions clés en flashcards mémorisables.","it-IT":"Distilla concetti e conclusioni chiave in flashcard memorizzabili.","pl-PL":"Przełóż kluczowe pojęcia i wnioski na fiszki łatwe do zapamiętania.","pt-BR":"Destile conceitos e conclusões-chave em flashcards memorizáveis.","ru-RU":"Дистиллируй ключевые понятия и выводы в карточки для запоминания.","tr-TR":"Temel kavramları ve sonuçları ezberlenebilir soru-cevap kartlarına dönüştür.","ca-ES":"Destil·la conceptes i conclusions clau en flashcards memoritzables.","bn-IN":"মূল ধারণা ও সিদ্ধান্তকে সহজে মুখস্থযোগ্য প্রশ্ন-উত্তর কার্ডে রূপ দিন।"}),
]

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

def build_block(locale):
    top: dict = {}
    for dotted, table in KEYS:
        parts = dotted.split('.')
        node = top
        for p in parts[:-1]:
            node = node.setdefault(p, {})
        node[parts[-1]] = table[locale]

    def render(node, indent):
        out = []
        pad = '  ' * indent
        for k, v in node.items():
            if isinstance(v, dict):
                out.append(f"{pad}{k}: {{")
                out.extend(render(v, indent + 1))
                out.append(f"{pad}}},")
            else:
                out.append(f'{pad}{k}: "{esc(v)}",')
        return out

    # render both namespaces as siblings
    out = []
    for ns in ("geminiSources", "geminiStudio"):
        if ns in top:
            out.append(f"  {ns}: {{")
            out.extend(render(top[ns], 2))
            out.append("  },")
    return "\n".join(out)

base = "frontend/src/lib/locales"
for loc in LOCALES:
    path = os.path.join(base, loc, "index.ts")
    with io.open(path, "r", encoding="utf-8") as f:
        text = f.read()
    if "geminiSources:" in text:
        print(f"skip {loc} (already present)")
        continue
    anchor = "} satisfies TranslationShape;"
    idx = text.rfind(anchor)
    if idx == -1:
        # en-US defines the shape itself: insert before the closing "}" of
        # `export const enUS = { ... }` (the last line that is exactly "}").
        lines = text.split("\n")
        close = max(i for i, ln in enumerate(lines) if ln == "}")
        block = build_block(loc).split("\n")
        lines = lines[:close] + block + lines[close:]
        text = "\n".join(lines)
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"ok {loc} (shape source, before closing brace line {close + 1})")
        continue
    block = build_block(loc) + "\n"
    text = text[:idx] + block + text[idx:]
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"ok {loc}")
